theme: jekyll-theme-minimal

title: "Maximin Coavoux"

markdown: kramdown

sidetext: |
    <p>CNRS Researcher (Chargé de recherche)</p>
    <p>Laboratoire d'Informatique de Grenoble (LIG), Université Grenoble-Alpes</p> 

extralinks: |
    <li><a href="https://scholar.google.com/citations?user=boYvx48AAAAJ&hl=fr"><img src="img/google-scholar.png" alt="google profile"/></a></li>
    <li><a href="https://cv.archives-ouvertes.fr/maximin-coavoux"><img src="img/hal.png" alt="CV HAL"/></a></li>
    <li><a href="https://gitlab.com/mcoavoux/"><img src="img/gitlab-icon-rgb.png" alt="Gitlab"/></a></li>
    <li><a href="https://www.aclweb.org/anthology/people/m/maximin-coavoux/"><img src="img/acl.png" alt="ACL Anthology"/></a></li>
